### ISSUE TITLE
Type 'T' does not satisfy the constraint 'IConfiguration'

### ISSUE THREAD

**Issue by JakobMadsen717** [microsoft/ApplicationInsights-JS#2065]
I have angular app that uses "@microsoft/applicationinsights-web": "3.0.0"

When I upgrade to "@microsoft/applicationinsights-web": "3.0.1", I get compile errors (on ng serve/build) of this type:
Error: node_modules/@microsoft/applicationinsights-core-js/types/applicationinsights-core-js.d.ts:905:85 - error TS2344: Type 'T' does not satisfy the constraint 'IConfiguration'.

So I downgrade to 3.0.0 for now where all works fine, but I am unsure if some bug was introduced in applicationinsights-core-js.d.ts in version 3.0.1?

**Comment by thomasfroehle** [comment]
Same here

**Comment by MSNev** [comment]
We have not yet released an AI v3.x compatibly version of the angular plugin
as per https://github.com/microsoft/applicationinsights-angularplugin-js#compatibility-matrix

I'm actually surprised that it is working with v3.0.0 [die to these](https://microsoft.github.io/ApplicationInsights-JS/upgrade/v3_BreakingChanges.html) as when using the angular plugin you are merging them and the angular plugin is not self contained)

We are planning on releasing an update version of the angular (and react) plugins this month (probably towards the end of the month). Which will use the version numbering [discussed here](https://github.com/microsoft/applicationinsights-angularplugin-js/issues/57)

**Comment by JakobMadsen717** [comment]
Just wanted to mention that I am not actually using @microsoft/applicationinsights-angularplugin-js in my angular app.
I am only using @microsoft/applicationinsights-web when I see the compilation error. Only wanted to mention it in case the compilation error when using @microsoft/applicationinsights-web in angular/typescript was unintentional. Feel free to ignore and I can look at things again at a later point in time.

**Comment by MSNev** [comment]
Umm, I have no idea what's going on with the following....

```ts
"@microsoft/applicationinsights-common": "^3.0.1",
"@microsoft/applicationinsights-web": "^3.0.1",
```

Version 3.0.1 now no longer includes references within themselves so they always reference the source packages.
`@microsoft/applicationinsights-web` is re-exporting `IConfiguration`  from `@microsoft/applicationinsights-core-js` and common doesn't seem to reference `IConfiguration`... And all references that I'm finding in the web package are importing the type from core-js (and not the re-exported version)...

**Comment by MSNev** [comment]
@Socolin can you do an `npm ls` and validate that only v3.0.1 of all of the `@microsoft/applicationinsights-XXXX` packages are installed -- its sounding like there is a version mismatch coming from somewhere.

**Comment by Socolin** [comment]
Here a repro if it help [ReproApplicationInsights-JS-2065.zip](https://github.com/microsoft/ApplicationInsights-JS/files/11492156/ReproApplicationInsights-JS-2065.zip)

npm ls
```
ReproApplicationInsights-JS-2065@1.0.0 /tmp/b/ReproApplicationInsights-JS-2065
├── @microsoft/applicationinsights-common@3.0.1
├── @microsoft/applicationinsights-web@3.0.1
└── typescript@5.0.4
```

**Comment by MSNev** [comment]
@Socolin 👍 THANK YOU for the repo project, it looks like this is cause by some differences with our constraints for some (not all) of the functions / interfaces that take objects which (may) be IConfiguration.

I'll review these from the repo (as we don't get this as part of the main build) to try and fix while also causing the existing build to fail with the same issue (somehow) -- so we don't repo this issue.

**Comment by MSNev** [comment]
Also back ported to v2.x https://github.com/microsoft/ApplicationInsights-JS/milestone/81

**Comment by JakobMadsen717** [comment]
Using 3.0.2 nightly builds (e.g. nightly3.2305-12) everything looks great to me, I now ts compile, build and run fine. Thanks much!
