### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/ApplicationInsights-JS#2369]
**Description/Screenshot**

One of our Azure SDK packages has a dependency on @microsoft/applicationinsights-web-snippet, after we upgrade from v1.1.2 to v1.2.0, we got this compilation error from TypeScript compiler.   Looks that your type definition reference @microsoft/applicationinsights-web, but it is only a dev dependency https://github.com/microsoft/ApplicationInsights-JS/blob/main/tools/applicationinsights-web-snippet/package.json#L35, so when users install @microsoft/applicationinsights-web-snippet they will not have @microsoft/applicationinsights-web

```
../../../common/temp/node_modules/.pnpm/@microsoft+applicationinsights-web-snippet@1.2.0/node_modules/@microsoft/applicationinsights-web-snippet/types/applicationinsights-web-snippet.d.ts:15:32 - error TS2307: Cannot find module '@microsoft/applicationinsights-web' or its corresponding type declarations.

15 import { IConfiguration } from '@microsoft/applicationinsights-web';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in ../../../common/temp/node_modules/.pnpm/@microsoft+applicationinsights-web-snippet@1.2.0/node_modules/@microsoft/applicationinsights-web-snippet/types/applicationinsights-web-snippet.d.ts:15
```

**Steps to Reproduce**
probably include @microsoft/applicationinsights-web-snippet 1.2.0 in a typescript project as a direct dependency then build the project

 - OS/Browser:
 - SDK Version [e.g. 22]:
 - How you initialized the SDK:

**Expected behavior**

No breaking changes between minor version increment. 

**Additional context**

**Comment by siyuniu-ms** [comment]
Hi, thanks for the information. We will make a new release which avoid the web package dependency.

**Comment by MSNev** [comment]
Note: that it will cause the definition of `IConfiguration` to be replaced with `any`, so you won't get any TypeScript type support for the `cfg` :-(.
The only way we can easily include the `IConfiguration` into the `web-snippet` is to either duplicate a lot of configurations, copy them during build, attempt to re-export them from the snippet, or move the `@microsoft/applicationinsights-web` to either a peerDependency (with a wide range) or as a dependency.

We had a previous issue where consumers did not want to have `@microsoft/applicationinsights-web` included as a direct dependency and I would assume also as a peerDependency (as this would require them to install it). So the quickest resolution is the `any` (for now) and we will look to add back support in a later release.

**Comment by siyuniu-ms** [comment]
https://www.npmjs.com/package/@microsoft/applicationinsights-web-snippet version 1.2.1 is published now.
